"""Add car table

Revision ID: 4da7188309b4
Revises: 72ee3f8e26c7
Create Date: 2022-05-02 00:51:29.250427

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4da7188309b4'
down_revision = '72ee3f8e26c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('doors', sa.Integer(), nullable=True),
    sa.Column('ac_included', sa.Boolean(), nullable=True),
    sa.Column('insurance', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('transmission', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_car_id'), 'car', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_car_id'), table_name='car')
    op.drop_table('car')
    # ### end Alembic commands ###
