"""Update user_id to user_emial in ApartmentReservation

Revision ID: 65cb583a7fc3
Revises: 550b09341b76
Create Date: 2022-05-21 00:28:39.285064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65cb583a7fc3'
down_revision = '550b09341b76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apartment_reservation', sa.Column('user_email', sa.String(), nullable=True))
    op.drop_constraint('apartment_reservation_user_id_fkey', 'apartment_reservation', type_='foreignkey')
    op.drop_column('apartment_reservation', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apartment_reservation', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('apartment_reservation_user_id_fkey', 'apartment_reservation', 'user', ['user_id'], ['id'])
    op.drop_column('apartment_reservation', 'user_email')
    # ### end Alembic commands ###
