"""Add email subscription

Revision ID: beb9b92989be
Revises: 5fde930fc9d1
Create Date: 2022-07-01 10:38:12.922977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'beb9b92989be'
down_revision = '5fde930fc9d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_subscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_subscription_id'), 'email_subscription', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_subscription_id'), table_name='email_subscription')
    op.drop_table('email_subscription')
    # ### end Alembic commands ###
