"""Alter date field in taxi reservation

Revision ID: c04fd4ab5e27
Revises: 40b8c784835c
Create Date: 2022-06-02 12:48:10.578734

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c04fd4ab5e27'
down_revision = '40b8c784835c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('taxi_reservation', sa.Column('from_date', sa.DateTime(), nullable=True))
    op.add_column('taxi_reservation', sa.Column('to_date', sa.DateTime(), nullable=True))
    op.drop_column('taxi_reservation', 'reservation_datetime')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('taxi_reservation', sa.Column('reservation_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('taxi_reservation', 'to_date')
    op.drop_column('taxi_reservation', 'from_date')
    # ### end Alembic commands ###
