"""Add addresses to taxi reservation

Revision ID: c63b63df3cd8
Revises: c04fd4ab5e27
Create Date: 2022-06-02 16:28:40.877668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c63b63df3cd8'
down_revision = 'c04fd4ab5e27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('taxi_reservation', sa.Column('start_address', sa.String(), nullable=True))
    op.add_column('taxi_reservation', sa.Column('end_address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('taxi_reservation', 'end_address')
    op.drop_column('taxi_reservation', 'start_address')
    # ### end Alembic commands ###
