"""Add new fields to ApartmentReservation

Revision ID: ceaf574dd9c4
Revises: 4da7188309b4
Create Date: 2022-05-19 19:31:30.789261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ceaf574dd9c4'
down_revision = '4da7188309b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apartment_reservation', sa.Column('guest_name', sa.String(), nullable=True))
    op.add_column('apartment_reservation', sa.Column('guest_phone', sa.String(), nullable=True))
    op.add_column('apartment_reservation', sa.Column('comment', sa.String(), nullable=True))
    op.add_column('apartment_reservation', sa.Column('arriving_time', sa.Time(), nullable=True))
    op.add_column('apartment_reservation', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'apartment_reservation', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'apartment_reservation', type_='foreignkey')
    op.drop_column('apartment_reservation', 'user_id')
    op.drop_column('apartment_reservation', 'arriving_time')
    op.drop_column('apartment_reservation', 'comment')
    op.drop_column('apartment_reservation', 'guest_phone')
    op.drop_column('apartment_reservation', 'guest_name')
    # ### end Alembic commands ###
