"""Add taxi entities

Revision ID: d8c7e4108d9e
Revises: f210ca418825
Create Date: 2022-05-29 16:27:12.736256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8c7e4108d9e'
down_revision = 'f210ca418825'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('taxi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('luggage_capacity', sa.Integer(), nullable=True),
    sa.Column('price_for_km', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_taxi_id'), 'taxi', ['id'], unique=False)
    op.create_table('taxi_reservation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reservation_date', sa.DateTime(), nullable=True),
    sa.Column('appeal', sa.String(), nullable=True),
    sa.Column('user_name', sa.String(), nullable=True),
    sa.Column('user_phone', sa.String(), nullable=True),
    sa.Column('user_email', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('taxi_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['taxi_id'], ['taxi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_taxi_reservation_id'), 'taxi_reservation', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_taxi_reservation_id'), table_name='taxi_reservation')
    op.drop_table('taxi_reservation')
    op.drop_index(op.f('ix_taxi_id'), table_name='taxi')
    op.drop_table('taxi')
    # ### end Alembic commands ###
